config/routes.rb
Rails.application.routes.draw do
  resources :cards

  root 'cards#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
  after_initialize :set_default, if: :new_record?
  
  scope :date_between, -> from, to do
    if from.present? && to.present?
      where(date: from..to)
    elsif from.present?
      where('date >= ?', from)
    elsif to.present?
      where('date <= ?', to)
    end
  end
  
  private
  def set_default 
    d = Time.now
    self.date ||= Date.today
    self.start ||= Time.local(d.year, d.month, d.day, 9, 30, 0)
    self.end ||= Time.local(d.year, d.month, d.day, 18, 30, 0)
    self.reststart ||= Time.local(d.year, d.month, d.day, 12, 0, 0)
    self.restend ||= Time.local(d.year, d.month, d.day, 13, 0, 0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  http_basic_authenticate_with :name => ENV['BASIC_AUTH_USERNAME'], :password => ENV['BASIC_AUTH_PASSWORD'] if Rails.env == "production"
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    year_month = params[:year_month]
    d = Date.today
    
    if year_month
      d_t = Date.new(year_month[0..3].to_i, year_month[-2..-1].to_i, 1)
      d_s = Date.new(d_t.last_month.year, d_t.last_month.month, 26)
      d_e = Date.new(d_t.year, d_t.month, 25)
    elsif d.day > 25
      d_s = d
      d_e = d.next_month
    else
      d_s = d.last_month
      d_e = d
    end
    
    d_start = Date.new(d_s.year, d_s.month, 26)
    d_end = Date.new(d_e.year, d_e.month, 25)
    @cards = Card.date_between(d_start, d_end).order("date DESC")
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    @cost = params[:cost]
    to = params[:to]
    cc = params[:cc]

    respond_to do |format|
      if @card.save
        UserMailer.registration_confirmation(@card, @cost, to, cc).deliver_later
        format.html { redirect_to cards_url, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:date, :start, :end, :reststart, :restend)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card, html:{class:"form-horizontal col-md-8 col-md-offset-2"}) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="card_date" class="col-sm-3 control-label">日付</label>
    <div class="col-md-6">
    <%= f.text_field :date, class: "form-controll date-picker" %>
    </div>
  </div>

  <div class="form-group">
    <label for="card_start" class="col-sm-3 control-label">出勤時刻</label>
    <div class="col-md-6">
    <%= f.time_select :start, class: "form-controll" %>
    </div>
  </div>
  
  <div class="form-group">
    <label for="card_end" class="col-sm-3 control-label">退勤時刻</label>
    <div class="col-md-6">
    <%= f.time_select :end, class: "form-controll" %>
    </div>
  </div>

  <div class="form-group">
    <label for="card_reststart" class="col-sm-3 control-label">休憩開始時刻</label>
    <div class="col-md-6">
    <%= f.time_select :reststart, class: "form-controll" %>
    </div>
  </div>
  
  <div class="form-group">
    <label for="card_restend" class="col-sm-3 control-label">休憩終了時刻</label>
    <div class="col-md-6">
    <%= f.time_select :restend, class: "form-controll" %>
    </div>
  </div>

  <div class="form-group">
    <label for="card_cost" class="col-sm-3 control-label">交通費</label>
    <div class="col-md-6">
    <%= text_field_tag :cost, '0', class: "form-controll" %>
    </div>
  </div>

  <div class="form-group">
    <label for="card_to" class="col-sm-3 control-label">TO:</label>
    <div class="col-md-6">
    <%= text_field_tag :to, '', class: "form-controll" %>
    </div>
  </div>

  <div class="form-group">
    <label for="card_cc" class="col-sm-3 control-label">CC:</label>
    <div class="col-md-6">
    <%= text_field_tag :cc, '', class: "form-controll" %>
    </div>
  </div>

  <div class="actions">
    <div class="col-md-2 col-md-offset-3">
    <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/cards/_table_row.html.erb
<%
rest_time = ((card.restend - card.reststart) / 3600).round(1)
work_time = (((card.end - card.start) - (card.restend - card.reststart)) / 3600).round(1)
salary = work_time * 2000
@sum_salary += salary
@sum_time += work_time
%>
<tr>
  <td><%= card.date.to_s(:published_md) %></td>
  <td><%= card.start.to_s(:published_time) %></td>
  <td><%= card.end.to_s(:published_time) %></td>
  <td><%= work_time %></td>
  <td><%= salary.round %></td>
  <td><%= link_to 'Edit', edit_card_path(card), class: 'btn btn-default btn-xs' %></td>
  <td><%= link_to card, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs', :method => :delete do %>
    <i class="glyphicon glyphicon-minus"></i>
  <% end %></td>
</tr>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<div class="rows">
  
  <p id="notice"><%= notice %></p>
  
  <table class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th>Date</th>
        <th>Attend</th>
        <th>Quit</th>
        <th>Time</th>
        <th>Wage</th>
        <th colspan="2"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @sum_salary = 0; @sum_time = 0; @cards.each do |card| %>
        <%= render partial: 'table_row', locals: {card: card} %>
      <% end %>
    </tbody>
  </table>
  
  <p>出勤日数: <strong><%= @cards.count %></strong></p>
  <p>合計労働時間: <strong><%= @sum_time.round %></strong></p>
  <p>合計金額: <span class="glyphicon glyphicon-jpy" aria-hidden="true"></span><strong><%= @sum_salary.round %></strong></p>
  
  <br>

</div>

app/views/cards/new.html.erb
<h1>New Card</h1>

<div class="row">
<%= render 'form' %>
</div>

<div class="row">
<%= link_to 'Back', cards_path %>
</div>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @card.date %>
</p>

<p>
  <strong>Start:</strong>
  <%= @card.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @card.end %>
</p>

<p>
  <strong>Reststart:</strong>
  <%= @card.reststart %>
</p>

<p>
  <strong>Restend:</strong>
  <%= @card.restend %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">TimeCard</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to 'New', new_card_path %></li>
      </ul>
        <%
        # pre: 201602, nex: 201512 など
        if !params[:year_month]
          if Date.today.day > 25
            tod = Date.today.next_month
          else
            tod = Date.today
          end
        else
          tod = Date.new(params[:year_month][0..3].to_i, params[:year_month][-2..-1].to_i, 1)
        end
        pre = tod.last_month.year.to_s + sprintf("%02d", tod.last_month.month)
        nex = tod.next_month.year.to_s + sprintf("%02d", tod.next_month.month)
        %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "前月", cards_path(year_month: pre) %></li>
        <li><%= link_to "次月", cards_path(year_month: nex) %></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <%= yield %>
</div>

</body>
</html>